// swift-tools-version: 5.9
//
// The sleep differential generator. It runs upstream's own Swift pipeline over synthetic nights
// and writes the inputs and golden outputs that `SleepDifferentialTest` compares the Kotlin port
// against. Gradle never runs this; it is regenerated by hand with `regenerate.sh`.
//
// Built ONLY from the temporary layout `regenerate.sh` creates, where `../OpenCircuitKit` is a
// copy of upstream's package at the pinned commit. It does not build in place.
import PackageDescription

let package = Package(
    name: "SleepDifferential",
    dependencies: [
        .package(name: "OpenCircuitKit", path: "../OpenCircuitKit"),
    ],
    targets: [
        .executableTarget(
            name: "SleepDifferential",
            dependencies: [.product(name: "OpenCircuitKit", package: "OpenCircuitKit")]
        ),
    ]
)
