// swift-tools-version: 5.9
//
// The differential generators. Each runs upstream's own Swift code over synthetic inputs and writes
// the inputs and golden outputs a Kotlin test compares the port against:
//   SleepDifferential  → the sleep pipeline, read by `SleepDifferentialTest`
//   VitalsDifferential → the vitals and energy maths, read by `VitalsDifferentialTest`
//   EngineDifferential → named sites of the trends, alert, headache, cycle and proximity engines,
//                        read by `EngineDifferentialTest`
// Gradle never runs these; they are regenerated by hand with `regenerate.sh [sleep|vitals|engine]`.
//
// Built ONLY from the temporary layout `regenerate.sh` creates, where `../OpenCircuitKit` is a
// copy of upstream's package at the pinned commit. It does not build in place.
import PackageDescription

let package = Package(
    name: "SleepDifferential",
    dependencies: [
        .package(name: "OpenCircuitKit", path: "../OpenCircuitKit"),
    ],
    targets: [
        .executableTarget(
            name: "SleepDifferential",
            dependencies: [.product(name: "OpenCircuitKit", package: "OpenCircuitKit")]
        ),
        .executableTarget(
            name: "VitalsDifferential",
            dependencies: [.product(name: "OpenCircuitKit", package: "OpenCircuitKit")]
        ),
        .executableTarget(
            name: "EngineDifferential",
            dependencies: [.product(name: "OpenCircuitKit", package: "OpenCircuitKit")]
        ),
    ]
)
